#! /bin/sh
#$PANEL_FIFO=/home/shit-twins/.panel.fifo

# config options
bspc config border_width	5
bspc config window_gap	20
bspc config top_padding	40
bspc config bottom_padding 	5
bspc config right_padding 	10
bspc config left_padding 	10
bspc config split_ratio      	0.50
bspc config borderless_monocle	true
bspc config gapless_monocle     	true
bspc config focus_follows_pointer	true
bspc config auto_alternate		true
bspc config auto_cancel		true

#rules
bspc rule -a "urxvt" desktop=term floating=on center=true
bspc rule -a "Firefox" desktop=web sticky=off
bspc rule -a "sublime_text" desktop=files
bspc rule -a "pcmanfm" desktop=files
bspc rule -a "soulseekqt" desktop=files
bspc rule -a "puddletag" desktop=files
bspc rule -a "steam" desktop=games pseudo_tiled=on
bspc rule -a Gimp desktop=shit follow=on floating=on
bspc rule -a mplayer floating=true
bspc rule -a Screenkey manage=off
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a feh floating=on center=true
bspc rule -a lxappearance floating=on center=true
bspc rule -a xfontsel floating=on center=true
bspc rule -a sxiv floating=true center=true
bspc rule -a Conky sticky=on manage=off lower=on

#colours
bspc config normal_border_color 	"#02151B"
bspc config active_border_color 		"#FF6666"
bspc config focused_border_color 	"#FF6666"
bspc config presel_border_color 		"#9a875f"
bspc config urgent_border_color 	"#9f7155"
bspc config focused_locked_border_color "#9a875f"

# desktops
bspc monitor -d term web files games shit

# Autostart apps
~/.config/bspwm/panel &