#! /bin/sh
#$PANEL_FIFO=/home/ε-twins/.panel.fifo

# config options
bspc config border_width	4
bspc config window_gap	5
bspc config top_padding	0
bspc config bottom_padding 	0
bspc config right_padding 	250
bspc config left_padding 	0
bspc config split_ratio      	0.50
bspc config borderless_monocle	true
bspc config gapless_monocle     	true
bspc config focus_follows_pointer	true
bspc config auto_alternate		true
bspc config auto_cancel		true

#rules
bspc rule -a "urxvt" desktop=一 floating=on
bspc rule -a "Firefox" desktop=二 sticky=off
bspc rule -a "sublime_text" desktop=三
bspc rule -a "pcmanfm" desktop=三
bspc rule -a "puddletag" desktop=三
bspc rule -a "soulseekqt" desktop=四
bspc rule -a "steam" desktop=四 pseudo_tiled=on
bspc rule -a Gimp desktop=五 follow=on floating=on
bspc rule -a mplayer floating=true
bspc rule -a Screenkey manage=off
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a feh floating=on center=true
bspc rule -a lxappearance floating=on center=true
bspc rule -a xfontsel floating=on center=true
bspc rule -a sxiv floating=true center=true
bspc rule -a Conky sticky=on manage=off lower=on

#colours
bspc config normal_border_color 	"#30303a"
bspc config active_border_color 		"#ad6a72"
bspc config focused_border_color 	"#ad6a72"
bspc config presel_border_color 		"#9a875f"
bspc config urgent_border_color 	"#9f7155"
bspc config focused_locked_border_color "#9a875f"

# desktops
bspc monitor -d 一 二 三 四 五 六

# Autostart apps
~/.config/bspwm/panel &
