#!/bin/sh
cd $(dirname $0)
if [ $(pgrep -cx panel) -gt 1 ]; then
printf "%s\n" 'The panel is already running.' >&2
exit 1
else
# just so I know it's working
printf 'Now running...\n'
fi
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT
# make space for panel
PANEL_HEIGHT=20
bspc config top_padding 0
# load colors for defining Dzen2 BG and FG
source ./panel_colors
# run Dzen2 with BSPWM info
bspc control --subscribe | ~/.config/bspwm/panel_dzen2 | dzen2 -x 1121 -y 5 -w 240 -h 30 -ta 'c' -title-name 'panel' -fn '-*-m+ 1c-bold-r-*-*-13-*-*-*-*-*-iso10646-1,' -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
# run Dzen2 with Conky info
conky -c ~/conkys/smallbar | dzen2 -x 1121 -y 620 -w 240 -h 30 -ta 'r' -title-name 'panel' -fn '-*-m+ 1c-bold-r-*-*-13-*-*-*-*-*-iso10646-1' -fg "#726a78" -bg "$COLOR_BACKGROUND" &
wait